import { SITE_URL } from "@/lib/config";

export interface RobotsOptions {
  blockedAgents: string[]; // exact user-agent tokens
  sitemapUrls?: string[];
  crawlDelays?: Record<string, number>; // agent name -> seconds
}

const HEADER_LINES = [
  `# robots.txt generated by OpenRobots — ${SITE_URL}`,
  "# Decide how AI sees your site.",
];

interface RuleGroup {
  agents: string[];
  rules: string[];
}

/**
 * Generates a robots.txt from the given options.
 *
 * - No blocked agents -> permissive file ("User-agent: *" / "Allow: /").
 * - Blocked agents without a crawl-delay share one group (multiple
 *   "User-agent:" lines followed by a single "Disallow: /").
 * - Blocked agents with a crawl-delay get their own group so the
 *   Crawl-delay directive applies only to them. Crawl-delays for agents
 *   that are not blocked are ignored.
 */
export function generateRobots(opts: RobotsOptions): string {
  const { blockedAgents, sitemapUrls = [], crawlDelays = {} } = opts;

  // Dedupe while preserving order.
  const blocked = [...new Set(blockedAgents.map((name) => name.trim()).filter(Boolean))];

  const groups: RuleGroup[] = [];
  if (blocked.length === 0) {
    groups.push({ agents: ["*"], rules: ["Allow: /"] });
  } else {
    const delayed: RuleGroup[] = [];
    const rest: string[] = [];
    for (const name of blocked) {
      const delay = crawlDelays[name];
      if (typeof delay === "number" && Number.isFinite(delay) && delay > 0) {
        delayed.push({ agents: [name], rules: ["Disallow: /", `Crawl-delay: ${delay}`] });
      } else {
        rest.push(name);
      }
    }
    if (rest.length > 0) groups.push({ agents: rest, rules: ["Disallow: /"] });
    groups.push(...delayed);
  }

  const lines: string[] = [...HEADER_LINES];
  groups.forEach((group, index) => {
    if (index > 0) lines.push("");
    for (const agent of group.agents) lines.push(`User-agent: ${agent}`);
    lines.push(...group.rules);
  });

  const sitemaps = sitemapUrls.map((url) => url.trim()).filter(Boolean);
  if (sitemaps.length > 0) {
    lines.push("");
    for (const url of sitemaps) lines.push(`Sitemap: ${url}`);
  }

  return lines.join("\n") + "\n";
}
