import { describe, expect, it } from "vitest";
import { generateRobots } from "@/lib/robots";

const HEADER =
  "# robots.txt generated by OpenRobots — https://openrobots.vercel.app\n" +
  "# Decide how AI sees your site.\n";

describe("generateRobots", () => {
  it("returns a permissive robots.txt when no agents are blocked", () => {
    expect(generateRobots({ blockedAgents: [] })).toBe(
      HEADER + "User-agent: *\nAllow: /\n",
    );
  });

  it("groups multiple blocked agents under one Disallow (contract §6 format)", () => {
    expect(generateRobots({ blockedAgents: ["GPTBot", "ClaudeBot"] })).toBe(
      HEADER + "User-agent: GPTBot\nUser-agent: ClaudeBot\nDisallow: /\n",
    );
  });

  it("emits Sitemap lines after a blank line", () => {
    expect(
      generateRobots({
        blockedAgents: ["GPTBot"],
        sitemapUrls: ["https://example.com/sitemap.xml"],
      }),
    ).toBe(
      HEADER +
        "User-agent: GPTBot\nDisallow: /\n\nSitemap: https://example.com/sitemap.xml\n",
    );
  });

  it("emits one Sitemap line per URL", () => {
    const out = generateRobots({
      blockedAgents: [],
      sitemapUrls: ["https://a.com/s.xml", "https://b.com/s.xml"],
    });
    expect(out).toContain("Sitemap: https://a.com/s.xml\nSitemap: https://b.com/s.xml");
  });

  it("gives agents with a crawl-delay their own group", () => {
    expect(
      generateRobots({
        blockedAgents: ["GPTBot", "ClaudeBot"],
        crawlDelays: { ClaudeBot: 10 },
      }),
    ).toBe(
      HEADER +
        "User-agent: GPTBot\nDisallow: /\n\n" +
        "User-agent: ClaudeBot\nDisallow: /\nCrawl-delay: 10\n",
    );
  });

  it("ignores crawl-delays for agents that are not blocked", () => {
    const out = generateRobots({ blockedAgents: [], crawlDelays: { GPTBot: 5 } });
    expect(out).toBe(HEADER + "User-agent: *\nAllow: /\n");
  });

  it("deduplicates agent names while preserving order", () => {
    const out = generateRobots({ blockedAgents: ["GPTBot", "GPTBot", "CCBot", "GPTBot"] });
    expect(out).toContain("User-agent: GPTBot\nUser-agent: CCBot\nDisallow: /");
  });

  it("trims and drops empty agent names", () => {
    expect(generateRobots({ blockedAgents: ["  ", "GPTBot"] })).toBe(
      HEADER + "User-agent: GPTBot\nDisallow: /\n",
    );
  });
});
